version: "3.6"
services:
  db:
    image: "postgres:13"
    container_name: "my_postgres"
    ports:
      - "54320:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - my_pgdata:/var/lib/postgresql/data
volumes:
  my_pgdata: